<img style="float: left; margin: 30px 15px 15px 15px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzQj91sOlkeDFkg5HDbjtR4QJYmLXkfMNig&usqp=CAU" width="400" height="500" /> 
    
    
### <font color='navy'> Simulación matemática. 

**Nombres:** Sindy Citlali Sánchez Ponce, Carolina Anidsel Casillas García.

**Fecha:** 14 de septiembre del 2022.

**Expediente** : **740286**.
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/CarolinaCasillas/T3SindySanchez_CarolinaCasillas

# Tarea 3

### 1. Otro problema de transporte

La empresa Carbones de oriente debe ingresar a la empresa un requerimiento mínimo diario de carbón de $5000$ kg de carbón de alto volátil, $4000$ kg de medio volátil y $3000$ kg de bajo volátil para su debido proceso y trasformación. 

La entrada de estos se da en la siguiente tabla (los valores corresponden a un viaje en kg): 

-|Alto volátil|Medio volátil|Bajo volátil
:----|----|----|----
Mina sur|80|70|65
Mina norte|60|50|40
Mina central|40|30|20

El costo del trasporte de un viaje de cada mina es de 2500 dólares, 1500 dólares y 900 dólares, respectivamente. ¿Cuántos viajes de cada mina se deben recibir a diario para suplir los requerimientos mínimos y generar el menor costo de transporte? 

Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central  


El objetivo consiste consiste en plantear el problema de programación lineal que permita satisfacer los requerimientos de la empresa Carbones de oriente y resolverlo con `linprog`.

### 2. 
Una empresa de muebles rústicos fabrica entre muchos otros productos cinco tipos de sillas A, B, C, D Y E, las cuales se venden a precio de $1100$, $1300$, $1200$, $980$ y $1010$ pesos cada una y respectivamente. 

Las sillas pasan por cinco procesos: corte, ensamblado, lijado, pintado y sellado, para lo cual se dispone máximo de $17$, $11$, $15$, $12$ y $14$ horas respectivamente a la semana para dedicar a estas operaciones a estos productos.

Los requerimientos, en horas, para cada una de las sillas está dado en la siguiente tabla:

-|Corte|Ensamblado|Lijado|Pintado|Sellado
:----|----|----|----|----|----
Silla A|3|1|3|1|1
Silla B|2|3|2|2|3
Silla C|5|2|2|3|1
Silla D|2|4|1|1|2
Silla E|1|0|2|2|3

¿Cuántas sillas de cada tipo se deben fabricar para suplir los requerimientos de disponibiladas semanal y generar la mayor utilidad en ventas? 

Para simplificar la notación use las siguientes variables: 

+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E


El objetivo consiste consiste en plantear el problemade programación lineal que permita satisfacer los requerimientos de la empresa empresa de muebles y resolverlo con `linprog`.


Código de solución estudiante 1

In [ ]:
# Código de solución estudiante 1
.
.
.
.


### Respuesta planteada en el ejercicio usando (markdown)
 La respuesta es .........

Código de solución estudiante 2

In [31]:
#Importar numpy y el módulo optimize de la librería scipy
import numpy as np 
import scipy.optimize as opt

In [32]:
#Ejercicio 1
# Crear las matrices para resolver el problema
c = np.array([2500,1500,900])
b = np.array([-5000,-4000,-3000])
A = np.array([[-80,-60,-40],
             [-70,-50,-30],
             [-65,-40,-20]])

In [33]:
c,b,A

(array([2500, 1500,  900]),
 array([-5000, -4000, -3000]),
 array([[-80, -60, -40],
        [-70, -50, -30],
        [-65, -40, -20]]))

In [34]:
sol_ej1 = opt.linprog(c,A,b,method='simplex')

In [35]:
sol_ej1

     con: array([], dtype=float64)
     fun: 119999.99999999999
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([ 0.00000000e+00, -4.54747351e-13,  0.00000000e+00])
  status: 0
 success: True
       x: array([ 0., 50., 50.])

In [36]:
#Ejercicio 2
# Crear las matrices para resolver el problema
c = np.array([-1100,-1300,-1200.,-980,-1010])
b = np.array([17,11,15,12,14])
A = np.array([[3,2,5,2,1],
             [1,3,2,4,0],
             [3,2,2,1,2],
             [1,2,3,1,2],
             [1,3,1,2,3]])

In [37]:
c,b,A

(array([-1100., -1300., -1200.,  -980., -1010.]),
 array([17, 11, 15, 12, 14]),
 array([[3, 2, 5, 2, 1],
        [1, 3, 2, 4, 0],
        [3, 2, 2, 1, 2],
        [1, 2, 3, 1, 2],
        [1, 3, 1, 2, 3]]))

In [38]:
sol_ej2 = opt.linprog(c, A, b)

In [39]:
sol_ej2

     con: array([], dtype=float64)
     fun: -7699.999999956599
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([7.63478170e-11, 4.03233003e-12, 9.50599599e-11, 1.70071957e-10,
       7.64099894e-11])
  status: 0
 success: True
       x: array([2., 1., 1., 1., 2.])

### Respuesta planteada en el ejercicio usando (markdown)





 #### Estudiante 2
 ##### Ejercicio 1
 Nuestra función de utilidad es:
 
 $  2500x_{1} +1500 x_{2} + 900x_{3} $
 
 Restricciones: 
 
1. Se debe cumplir con al menos **5000 kg** de carbón **Alto volatil**: $80x_{1} + 60x_{2} + 40x_{3} \geq 5000$
2. Se debe cumplir con al menos **4000 kg** de carbón **Medio volatil**: $70x_{1} + 50x_{2} + 30x_{3} \geq 4000$
3. Se debe cumplir con al menos **3000 kg** de carbón **Bajo volatil**:$65x_{1} + 40x_{2} + 20x_{3} \geq 3000$
 
Cambiamos el signo de las ecuaciones para cambiar la igualdad.

 $\boldsymbol{c}=\left[2500 \quad 1500 \quad 900\right]^\top$,
 
 $\boldsymbol{A}=\left[\begin{array}{cc} -80 & -60 & -40 \\ -70 & -50 & -30 \\ -65 & -40 & -20 \end{array}\right]$, y
 
 $\boldsymbol{b}=\left[-5000 \quad -4000\quad -3000\right]^\top$.
 
Como resultado se obtiene un costo mínimo de $120000 con **50** viajes de la **Mina norte** y **50** viajes de la **Mina central**. El algoritmo arroja que no se deben realizar viajes de la Mina Sur.
 
 ##### Ejercicio 2
 
 Nuestra función de utilidad es:
 
 $ 1100 x_{a} +1300 x_{b} + 1200x_{c} +980x_{d} + 1010x_{e}$
 
 Restricciones: 
 
1. El tiempo de **Corte** debe ser menor a **17**: $3x_{a} + 2x_{b} + 5x_{c} + 2x_{d} + 1x_{e} \leq 17$
2. El tiempo de **Ensamblado** debe ser menor a **11**: $1x_{a} + 3x_{b} + 2x_{c} + 4x_{d} + 0x_{e} \leq 11$
3. El tiempo de **Lijado** debe ser menor a **15**: $3x_{a} + 2x_{b} + 2x_{c} + 1x_{d} + 2x_{e} \leq 15$
4. El tiempo de **Pintado** debe ser menor a **12**: $1x_{a} + 2x_{b} + 3x_{c} + 1x_{d} + 2x_{e} \leq 12$
5. El tiempo de **Sellado** debe ser menor a **14**: $1x_{a} + 3x_{b} + 1x_{c} + 2x_{d} + 3x_{e} \leq 14$
 
Como es un problema donde buscamos maximizar los beneficios, multiplicamos c por -1.

 $\boldsymbol{c}=\left[-1100 \quad -1300 \quad -1200 \quad -980 \quad -1010\right]^\top$,
 
 $\boldsymbol{A}=\left[\begin{array}{cc} 3 & 2 & 5 & 2 &1 \\ 1 & 3 & 2 & 4 & 0 \\ 3 & 2 & 2 & 1 & 2 \\ 1 & 2 & 3 & 1 & 2 \\ 1 & 3 & 1 & 2 & 3\end{array}\right]$, y
 
 $\boldsymbol{b}=\left[17 \quad 11\quad 15 \quad 12 \quad 14\right]^\top$.
 
Como resultado se obtiene una utilidad máxima de $7700 con la elaboracion de **2** sillas A, **1** silla B, **1** silla C, **1** silla D y **2** sillas D.